name: Bake and Push Docker Image

on:
  repository_dispatch:
    types: [wolfi-os-release]
  push:
    branches:
      - main
    paths:
      - 'rootfs/**'
      - 'Dockerfile'
      - 'Dockerfile.*'
      - 'docker-bake.hcl'
      - '.github/workflows/docker-bake.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  wolfi-digest:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.get.outputs.digest }}
    steps:
      - name: Set up skopeo
        uses: warjiang/setup-skopeo@main

      - name: Get Wolfi base image digest
        id: get
        run: |
          DIGEST=$(skopeo inspect --format='{{index .Digest}}' docker://cgr.dev/chainguard/wolfi-base:latest)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "Using latest Wolfi digest: $DIGEST"

  bake:
    runs-on: ubuntu-latest
    needs: wolfi-digest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set lowercase repo owner and name
        run: |
          echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/bake-action@v6
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_OWNER: ${{ env.IMAGE_OWNER }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          WOLFI_DIGEST:  ${{ needs.wolfi-digest.outputs.digest }}
        with:
          push: true
          pull: true
          targets: default
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  get-php-versions:
    runs-on: ubuntu-latest
    outputs:
      php-nts: ${{ steps.nts.outputs.php-versions }}
      php-zts: ${{ steps.zts.outputs.php-versions }}
      php-matrix: ${{ steps.combine.outputs.php-matrix }}
    steps:
      - name: Fetch PHP versions from Wolfi
        id: nts
        run: |
          VERSIONS=$(curl -sL https://packages.wolfi.dev/os/x86_64/APKINDEX.tar.gz \
            | tar -xOzf - APKINDEX \
            | grep -Po 'P:php-[0-9]+\.[0-9]+' \
            | sed 's/P:php-//' \
            | sort -u \
            | awk '$1 >= 8.1' \
            | jq -R . | jq -s . | tr -d '\n')
          echo "php-versions=$VERSIONS" >> $GITHUB_OUTPUT

      - name: Fetch PHP ZTS versions from Glimmer Labs
        id: zts
        run: |
          VERSIONS=$(curl -sL https://glimmer-labs.github.io/wolfi/x86_64/APKINDEX.tar.gz \
            | tar -xOzf - APKINDEX \
            | grep -Po 'P:php-[0-9]+\.[0-9]+-zts' \
            | sed 's/P:php-//' \
            | sort -u \
            | awk '$1 >= 8.1' \
            | jq -R . | jq -s . | tr -d '\n')
          echo "php-versions=$VERSIONS" >> $GITHUB_OUTPUT
      
      # Glimmer Labs already versions are outputed as "X.Y-zts", so we can combine both matrices directly
      - name: Combine PHP version matrices
        id: combine
        run: |
          NTS_VERSIONS='${{ steps.nts.outputs.php-versions }}'
          ZTS_VERSIONS='${{ steps.zts.outputs.php-versions }}'

          COMBINED_MATRIX=$(jq -s -c '.[0] + .[1]' <(echo "$NTS_VERSIONS") <(echo "$ZTS_VERSIONS"))

          echo "php-matrix=$COMBINED_MATRIX" >> $GITHUB_OUTPUT

  versioned-bake:
    runs-on: ubuntu-latest
    needs: [wolfi-digest, bake, get-php-versions]
    permissions:
      packages: write
    strategy:
      matrix:
        php-version: ${{ fromJSON(needs.get-php-versions.outputs.php-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set lowercase repo owner and name
        run: |
          echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME=$(echo '${{ github.repository }}' | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check if NTS or ZTS and set bake target
        run: |
          VERSION="${{ matrix.php-version }}"
          if [[ "$VERSION" == *"-zts" ]]; then
            echo "PHP_VERSION=${VERSION%-zts}" >> $GITHUB_ENV
            echo "TARGET=versioned-zts" >> $GITHUB_ENV
          else
            echo "PHP_VERSION=$VERSION" >> $GITHUB_ENV
            echo "TARGET=versioned" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/bake-action@v6
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_OWNER: ${{ env.IMAGE_OWNER }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          WOLFI_DIGEST:  ${{ needs.wolfi-digest.outputs.digest }}
          PHP_VERSION: ${{ env.PHP_VERSION }}
        with:
          push: true
          pull: true
          targets: ${{ env.TARGET }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max